name: Build and deploy website to Azure Web App - shahla-webapp-2026

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B40F0982B6BB437F9BF2AB8921AB22E8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8429BFDD885C40499CAF1B69FB685AD8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_31457C62D6384455B595154A1A67C861 }}

      - name: Deploy website to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shahla-webapp-2026'
          slot-name: 'Production'
